#!/opt/bin/bash
#    v 0.0.1, c plgroves gmail 2022
#    SCRIPTNAME 
#        runs after pia-wireguard service stop
#        disconnects from wireguard and shut down port forwarding
#        stop any vpn sensitive applications e.g. transmission
#        
####
# 
    _Usage() {
         sed >&2 -n "1d; /^###/q; /^#/!q; s/^#*//; s/^ //; 
                     s/SCRIPTNAME/${BASH_SOURCE##*/}/; p" \
                    "${BASH_SOURCE%/*}/${BASH_SOURCE##*/}"
         exit 1; }
    [[ "$1" =~ ^[-hH] ]] && _Usage "$@"

    function logger() {
        local message="${1}"; local source="${2:-${BASH_SOURCE}}"; local log="${3:-$LOG}"
        local tab spaces 
        tab="${TAB:-100}"
        IFS="" spaces="$(printf "%$((tab*2))s")"
        printf %s:[%s]:%.$((${tab}-${#source}))s%s%s  "$(date)" "$(cut -d- -f2- <<< "${source##*/}") " "${spaces} " "${message}" $'\n'| tee -a "${log}"
}

    log='/dev/null'
    LOG="${1:-${log}}"
    bash_source="${#BASH_SOURCE}"; export TAB=$((bash_source+1))

  # PIA's scripts are set to a relative path
    cd "${0%/*}" || exit 255

  # get $mydns?
    source .env 2>/dev/null

  # clear firewall
    logger "clearing firewall"
    iptables-restore < openrules.v4 

  # restore a sane DNS
    logger "restoring sane nameservers"
    cat <<-EOF > /etc/resolv.conf
    # Generated by PIA WIREGUARD
    nameserver ${mydns:-8.8.8.8}
    namesever 1.1.1.1
	EOF

  # disconnect VPN
    logger "Disconnecting from Private Internet Access"
    connmanctl disconnect "$(grep VPN < <( connmanctl services) | awk '{print $NF}')"

# add anything else such stopping applications and port forwarding

  # stop portforwarding 
    logger "stopping port forward binging"
    ps aux|grep '[p]f\.' | awk '{print $2}' | xargs kill >/dev/null 2>&1

exit 0
